server:
  port: 9000

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: DEBUG
    reactor:
      netty:
        http:
          client: DEBUG

lekhabook:
  jwtExpirationMs: 36000
  jwtSecret: thisismysecret
  servicesAcountUrl: http://lb-identity-service    

spring:
  application:
    name: lb-gw
  main:
    web-application-type: reactive
  cloud:
    ## address for consule
    consul:
      #uncoment on production      
      host: localhost
      port: 8500
      discovery:
        Prefer-ip-address: true
        instanceId: ${spring.application.name}-${server.port}-${spring.cloud.client.ip-address}

    gateway:
      x-forwarded:
        host-enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://erp.lekhabook.com,http://localhost:1100"
            allowedMethods:
            - GET
            - POST
            - POST
            - DELETE
            - PUT
      routes:
      # Route Mapping
      - id: lb-identity
        #uri: lb://lb-identity-service
        uri: http://localhost:10000
        predicates:
          - Path=/api/auth/**,/api/token/**,/api/users/**
        filters:
          - AuthClientFilter
          - PreserveHostHeader
          #- AuthorizationFilter
      - id: lekhabook-services
        uri: http://localhost:8000
        predicates:
          - Path=/api/**
        filters:
          - AuthClientFilter
          - AuthFilter
          - PreserveHostHeader
      - id: apps-services
        uri: http://localhost:1100
        predicates:
          - Path=/api/**
        filters:
          - AuthClientFilter
          - AuthFilter
          - PreserveHostHeader
      
