server:
  port: 9000

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: DEBUG
    reactor:
      netty:
        http:
          client: DEBUG

lekhabook:
  jwtExpirationMs: 36000
  jwtSecret: thisismysecret
  servicesAcountUrl: http://lb-identity-service    

spring:
  main:
    web-application-type: reactive
  cloud:
    ## address for consule
    consul:
      #uncoment on production
      host: consule-service
      #host: localhost
      port: 8500
      discovery:
        Prefer-ip-address: true
        instanceId: ${spring.application.name}-${server.port}-${spring.cloud.client.ip-address}

      gateway:
        x-forwarded:
          host-enabled: true
        globalcors:
          cors-configurations:
            '[/**]':
              allowedOrigins:
              - "http://localhost:1100"
              - "https://erp.lekhabook.com"
              - "https://apps-dev.lekhabook.com"
              - "https://contact-dev.lekhabook.com"
              - "http://localhost:44447"
              allowedMethods:
              - GET
              - POST
              - POST
              - DELETE
              - PUT
        routes:
        # Route Mapping
        - id: lb-identity
          uri: lb://lb-identity-service
          #uri: http://172.27.0.6:10000
          predicates:
            - Path=/api/auth/**,/api/token/**,/api/users/**
          filters:
            - AuthClientFilter
            - PreserveHostHeader
            #- AuthorizationFilter
        - id: lekhabook-services
          uri: lb://lb-erp-service
          predicates:
            - Path=/api/**
          filters:
            - AuthClientFilter
            - AuthFilter
            - PreserveHostHeader
